name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 添加 Gradle Wrapper 设置步骤
    - name: Setup Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip" > gradle/wrapper/gradle-wrapper.properties
        wget -P gradle/wrapper https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
        wget https://raw.githubusercontent.com/gradle/gradle/master/gradlew -O gradlew
        wget https://raw.githubusercontent.com/gradle/gradle/master/gradlew.bat -O gradlew.bat
        chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{steps.sign_app.outputs.signedReleaseFile}}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}