name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 创建并验证 Gradle Wrapper
    - name: Create Gradle Wrapper
      run: |
        # 创建目录
        mkdir -p gradle/wrapper
        
        # 下载 Gradle Wrapper JAR
        curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar
        
        # 创建 gradle-wrapper.properties
        echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        
        # 下载 gradlew 脚本
        curl -L -o gradlew https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradlew
        curl -L -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradlew.bat
        
        # 设置执行权限
        chmod +x gradlew
        
        # 验证文件
        ls -la gradle/wrapper/
        cat gradle/wrapper/gradle-wrapper.properties
        ls -la gradlew

    - name: Validate Gradle Wrapper
      run: |
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "gradle-wrapper.jar is missing!"
          exit 1
        fi
        if [ ! -f "gradle/wrapper/gradle-wrapper.properties" ]; then
          echo "gradle-wrapper.properties is missing!"
          exit 1
        fi
        if [ ! -x "gradlew" ]; then
          echo "gradlew is not executable!"
          exit 1
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease --info --stacktrace

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed-${{ github.sha }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}